[build]
  publish = "client/dist"
  command = "cd client && pnpm build"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "10.11.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cd client && pnpm dev"
  targetPort = 3000
  publish = "client/dist"